#ifndef HANCAT_H
#define HANCAT_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#ifdef _WIN32
#  ifdef HANCAT_EXPORTS
#    define HANCAT_API __declspec(dllexport)
#  else
#    define HANCAT_API __declspec(dllimport)
#  endif
#else
#  define HANCAT_API
#endif


/**
 * ## 마지막 에러 메시지를 반환하는 함수
 *
 * 에러가 없으면 빈 문자열을 반환합니다.
 * 반환된 포인터는 다음 hancat 함수 호출 전까지만 유효합니다.
 * `hancat_free()`로 해제하지 마세요.
 *
 * ### 사용 예시 (C)
 * ```c
 * char* result = hancat_modify(input);
 * if (!result) {
 *     const char* err = hancat_last_error();
 *     printf("에러: %s\n", err);
 * }
 * ```
 */
HANCAT_API const char *hancat_last_error(void);

/**
 * ## 문장 내의 모든 `{단어, 접사}` 패턴을 처리하여 변환된 문장을 반환하는 함수
 *
 * C에서 사용하는 `modify()` 함수입니다.
 * 반환된 문자열은 반드시 `hancat_free()`로 해제해야 합니다.
 *
 * - 접사가 어미이고 단어가 용언이면 용언 활용 처리
 * - 그 외에는 토시(조사) 처리
 * - 처리 실패 시 에러 코드(`{E01}`~`{E12}`)를 해당 위치에 삽입합니다.
 *
 * ### 매개변수
 * - `input`: 변환할 문장 (UTF-8 인코딩 C 문자열)
 *   - 형식: `"{단어, 접사} 문장"`
 *
 * ### 반환값
 * - 성공: 변환된 문장
 * - 실패: NULL (`hancat_last_error()`로 원인 조회)
 *
 * ### 사용 예시 (C)
 * ```c
 * // 토시(조사) + 용언 활용 통합 처리
 * char* r1 = hancat_modify("{철수, 이} {밥, 을} {먹다, 었습니다}.");
 * // r1: "철수가 밥을 먹었습니다."
 * hancat_free(r1);
 *
 * // 토시(조사)만 처리
 * char* r2 = hancat_modify("{철수, 은} {영희, 과} {밥, 를} 먹습니다.");
 * // r2: "철수는 영희와 밥을 먹습니다."
 * hancat_free(r2);
 *
 * // 용언만 처리
 * char* r3 = hancat_modify("여기서 {쉬다, 세요}.");
 * // r3: "여기서 쉬세요."
 * hancat_free(r3);
 * ```
 */
HANCAT_API
char *hancat_modify(const char *input);

/**
 * ## hancat 함수들이 반환한 문자열을 해제하는 함수
 *
 * `hancat_modify()`가 반환한 문자열을
 * 이 함수로 반드시 해제해야 합니다.
 *
 * ### 매개변수
 * - `s`: 해제할 문자열 포인터. NULL이면 무시합니다.
 *
 * ### 사용 예시 (C)
 * ```c
 * char* result = hancat_modify("{검, 을} 획득했습니다!");
 * printf("%s\n", result);
 * hancat_free(result);  // 반드시 해제
 * ```
 */
HANCAT_API void hancat_free(char *s);

#endif  /* HANCAT_H */
